ExecuteScreenLoadCode:
    lda RoomNumber
    jsr ChooseRoutine
        .word ScreenLoadCode00
        .word ScreenLoadCode01
        .word ScreenLoadCode02
        .word ScreenLoadCode03
        .word ScreenLoadCode04
        .word ScreenLoadCode05
        .word ScreenLoadCode06
        .word ScreenLoadCode07
        .word ScreenLoadCode08
        .word ScreenLoadCode09
        .word ScreenLoadCode0A
        .word ScreenLoadCode0B
        .word ScreenLoadCode0C
        .word ScreenLoadCode0D
        .word ScreenLoadCode0E
        .word ScreenLoadCode0F
        .word ScreenLoadCode10
        .word ScreenLoadCode11
        .word ScreenLoadCode12
        .word ScreenLoadCode13
        .word ScreenLoadCode14
        .word ScreenLoadCode15
        .word ScreenLoadCode16
        .word ScreenLoadCode17
        .word ScreenLoadCode18
        .word ScreenLoadCode19
        .word ScreenLoadCode1A
        .word ScreenLoadCode1B
        .word ScreenLoadCode1C
        .word ScreenLoadCode1D
        .word ScreenLoadCode1E
        .word ScreenLoadCode1F
        .word ScreenLoadCode20
        .word ScreenLoadCode21
        .word ScreenLoadCode22
        .word ScreenLoadCode23
        .word ScreenLoadCode24
        .word ScreenLoadCode25
        .word ScreenLoadCode26
        .word ScreenLoadCode27
        .word ScreenLoadCode28
        .word ScreenLoadCode29
        .word ScreenLoadCode2A
        .word ScreenLoadCode2B
        .word ScreenLoadCode2C
        .word ScreenLoadCode2D
        .word ScreenLoadCode2E
        .word ScreenLoadCode2F
        .word ScreenLoadCode30
        .word ScreenLoadCode31
        .word ScreenLoadCode32
        .word ScreenLoadCode33
        .word ScreenLoadCode34
        .word ScreenLoadCode35
        .word ScreenLoadCode36
        .word ScreenLoadCode37
        .word ScreenLoadCode38
        .word ScreenLoadCode39
        .word ScreenLoadCode3A
        .word ScreenLoadCode3B
        .word ScreenLoadCode3C
        .word ScreenLoadCode3D
        .word ScreenLoadCode3E
        .word ScreenLoadCode3F
        .word ScreenLoadCode40
        .word ScreenLoadCode41
        .word ScreenLoadCode42
        .word ScreenLoadCode43
        .word ScreenLoadCode44
        .word ScreenLoadCode45
        .word ScreenLoadCode46
        .word ScreenLoadCode47
        .word ScreenLoadCode48
        .word ScreenLoadCode49
        .word ScreenLoadCode4A
        .word ScreenLoadCode4B
        .word ScreenLoadCode4C
        .word ScreenLoadCode4D
        .word ScreenLoadCode4E
        .word ScreenLoadCode4F
        .word ScreenLoadCode50
        .word ScreenLoadCode51
        .word ScreenLoadCode52
        .word ScreenLoadCode53
        .word ScreenLoadCode54
        .word ScreenLoadCode55
        .word ScreenLoadCode56
        .word ScreenLoadCode57
        .word ScreenLoadCode58
        .word ScreenLoadCode59
        .word ScreenLoadCode5A
        .word ScreenLoadCode5B
        .word ScreenLoadCode5C
        .word ScreenLoadCode5D
        .word ScreenLoadCode5E
        .word ScreenLoadCode5F
        .word ScreenLoadCode60
        .word ScreenLoadCode61
        .word ScreenLoadCode62
        .word ScreenLoadCode63
        .word ScreenLoadCode64
        .word ScreenLoadCode65
        .word ScreenLoadCode66
        .word ScreenLoadCode67
        .word ScreenLoadCode68
        .word ScreenLoadCode69
        .word ScreenLoadCode6A
        .word ScreenLoadCode6B
        .word ScreenLoadCode6C
        .word ScreenLoadCode6D
        .word ScreenLoadCode6E
        .word ScreenLoadCode6F
        .word ScreenLoadCode70
        .word ScreenLoadCode71
        .word ScreenLoadCode72
        .word ScreenLoadCode73
        .word ScreenLoadCode74
        .word ScreenLoadCode75
        .word ScreenLoadCode76
        .word ScreenLoadCode77
        .word ScreenLoadCode78
        .word ScreenLoadCode79
        .word ScreenLoadCode7A
        .word ScreenLoadCode7B
        .word ScreenLoadCode7C
        .word ScreenLoadCode7D
        .word ScreenLoadCode7E
        .word ScreenLoadCode7F
