SongHeartHeader:
    SongHeader NoteLengthsTbl@6, $FF, $00, $04, $05
    .word @sq1, @sq2, @tri, @noise
    .byte $34, $34

@sq1:
    SongNoteLength $A
    SongRest
    SongRepeatSetup $3
        SongNoteLength $4
        SongNote "C#2"
        SongNote "G#2"
        SongNote "A2"
        SongNoteLength $3
        SongNote "G#2"
        SongNote "C3"
        SongNote "E2"
        SongNote "E2"
        SongNote "G#2"
        SongNote "G#2"
    SongRepeat
    SongNote "C#2"
    SongNote "G#5"
    SongNote "G#2"
    SongNote "G#5"
    SongNote "A2"
    SongNote "A5"
    SongNote "G#2"
    SongNote "G#5"
    SongNoteLength $5
    SongNote "E2"
    SongNoteLength $0
    SongRest
    SongNoteLength $A
    SongRest
    SongNoteLength $1
    SongNote "E2"
    SongNote "F2"
    SongNote "F#2"
    SongNote "G2"
    SongRepeatSetup $3
        SongNoteLength $1
        SongNote "G#2"
        SongNote "A2"
    SongRepeat
    SongNoteLength $2
    SongNote "G#2"
    SongNoteLength $A
    SongRest
    SongNoteLength $2
    SongNote "C#3"
    SongNote "E3"
    SongNote "G#3"
    SongNote "E3"
    SongNote "G#3"
    SongNote "C4"
    SongNote "D#4"
    SongNote "G#3"
    SongNote "A3"
    SongNote "E4"
    SongNote "C#4"
    SongNote "A3"
    SongNote "G#3"
    SongNote "D#4"
    SongNote "C4"
    SongNoteLength $7
    SongNote "G#3"
    SongNoteLength $A
    SongRest
    SongNoteLength $1
    SongNote "C#3"
    SongNote "B2"
    SongNote "C#3"
    SongNote "D#3"
    SongNote "E3"
    SongNote "D#3"
    SongNote "E3"
    SongNote "F#3"
    SongRepeatSetup $3
        SongNoteLength $1
        SongNote "G#3"
        SongNote "A3"
    SongRepeat
    SongNoteLength $A
    SongNote "G#3"
    SongNote "A3"
    SongNote "B3"
    SongNote "C4"
    SongNote "C#4"
    SongNote "D#4"
    SongNote "E4"
    SongNote "F#4"
    SongRepeatSetup $2
        SongNoteLength $6
        SongNote "G#4"
        SongNoteLength $1
        SongNote "F#4"
        SongNote "E4"
        SongNoteLength $6
        SongNote "D#4"
        SongNoteLength $1
        SongNote "C#4"
        SongNote "D#4"
        SongNoteLength $3
        SongNote "E4"
        SongNoteLength $1
        SongRest
        SongNoteLength $2
        SongNote "F#4"
        SongNoteLength $1
        SongNote "C#4"
        SongNoteLength $3
        SongNote "C#4"
        SongNote "D#4"
        SongNoteLength $0
        SongNote "A4"
        SongNote "G#4"
        SongNoteLength $2
        SongNote "C#4"
        SongNoteLength $0
        SongNote "A4"
        SongNote "G#4"
        SongNoteLength $2
        SongNote "C#4"
        SongNoteLength $0
        SongNote "A4"
        SongNote "G#4"
        SongNoteLength $1
        SongNote "C#4"
        SongNoteLength $0
        SongNote "G#4"
        SongNote "F#4"
        SongNoteLength $5
        SongNote "C4"
        SongNoteLength $0
        SongNote "G#3"
        SongNote "A3"
        SongNote "G#3"
        SongNote "A3"
        SongNoteLength $2
        SongNote "G#3"
    SongRepeat
    SongNoteLength $0
    SongNote "C#4"
    SongNote "C4"
    SongNoteLength $5
    SongNote "C#4"
    SongNoteLength $0
    SongNote "D#4"
    SongNote "C#4"
    SongNoteLength $5
    SongNote "D#4"
    SongNoteLength $0
    SongNote "E4"
    SongNote "D#4"
    SongNoteLength $2
    SongNote "E4"
    SongNoteLength $0
    SongNote "D#4"
    SongNote "E4"
    SongNoteLength $5
    SongNote "A4"
    SongNoteLength $0
    SongNote "G#4"
    SongNote "F#4"
    SongNoteLength $1
    SongNote "G#4"
    SongNote "F#4"
    SongNote "G#4"
    SongNote "A4"
    SongNote "G#4"
    SongNote "F#4"
    SongNote "G#4"
    SongNote "A4"
    SongNoteLength $6
    SongNote "G#4"
    SongNoteLength $1
    SongNote "F#4"
    SongNote "G#4"
    SongNote "A4"
    SongNote "G#4"
    SongNote "A4"
    SongNote "B4"
    SongNote "C#5"
    SongNote "B4"
    SongNote "A4"
    SongNote "G#4"
    SongNoteLength $6
    SongNote "A4"
    SongNoteLength $1
    SongNote "G#4"
    SongNote "A4"
    SongNote "C#5"
    SongNote "D#5"
    SongNoteLength $3
    SongNote "C#5"
    SongNoteLength $2
    SongNote "D#5"
    SongNoteLength $1
    SongNote "E5"
    SongNote "F#5"
    SongNoteLength $3
    SongNote "E5"
    SongNoteLength $2
    SongNote "F#5"
    SongRepeatSetup $2
        SongNoteLength $1
        SongNote "F#5"
        SongNote "D#5"
        SongNote "C5"
        SongNote "D#5"
        SongNote "C5"
        SongNote "G#4"
        SongNote "G4"
        SongNote "G#4"
    SongRepeat
    SongRepeatSetup $2
        SongNoteLength $1
        SongNote "D#4"
        SongNote "E4"
        SongNote "F#4"
        SongNote "G#4"
        SongNote "F#4"
        SongNote "E4"
        SongNoteLength $2
        SongNote "D#4"
    SongRepeat

@sq2:
    SongRepeatSetup $2
        SongNoteLength $4
        SongNote "C#3"
        SongNote "G#3"
        SongNote "A3"
        SongNoteLength $3
        SongNote "G#3"
        SongNote "C4"
        SongNote "E3"
        SongNote "E3"
        SongNote "G#3"
        SongNote "G#3"
    SongRepeat
    SongRepeatSetup $2
        SongNoteLength $6
        SongNote "E4"
        SongNoteLength $2
        SongNote "E4"
        SongNote "D#4"
        SongNoteLength $6
        SongNote "C4"
        SongNote "C#4"
        SongNoteLength $2
        SongNote "E4"
        SongNoteLength $1
        SongNote "C4"
        SongNote "C#4"
        SongNoteLength $6
        SongNote "D#4"
        SongNoteLength $5
        SongNote "E4"
        SongNoteLength $1
        SongNote "F#4"
        SongNote "E4"
        SongNote "D#4"
        SongNote "C#4"
        SongNoteLength $0
        SongNote "C#4"
        SongNote "D#4"
        SongNoteLength $2
        SongNote "E4"
        SongNote "D#4"
        SongNote "C#4"
        SongNote "D#4"
    SongRepeat
    SongNoteLength $3
    SongNote "C#2"
    SongNote "C#2"
    SongNote "G#2"
    SongNote "G#2"
    SongNote "A2"
    SongNoteLength $2
    SongNote "A2"
    SongNote "F#2"
    SongNoteLength $3
    SongNote "G#2"
    SongNote "G#2"
    SongNoteLength $4
    SongNote "F#2"
    SongRepeatSetup $4
        SongNoteLength $1
        SongNote "G#2"
        SongNote "A2"
    SongRepeat
    SongRepeatSetup $2
        SongNoteLength $6
        SongNote "G#2"
        SongNoteLength $2
        SongNote "C#3"
        SongNoteLength $6
        SongNote "D#3"
        SongNoteLength $2
        SongNote "C#3"
        SongNoteLength $6
        SongNote "E3"
        SongNoteLength $0
        SongRest
        SongRest
        SongNote "F#3"
        SongNote "E3"
        SongNoteLength $4
        SongNote "D#3"
        SongNote "C#3"
        SongNoteLength $3
        SongNote "C3"
        SongNoteLength $0
        SongNote "G#2"
        SongNote "G2"
        SongNote "G#2"
        SongNote "A2"
        SongNoteLength $2
        SongNote "G#2"
    SongRepeat
    SongNoteLength $3
    SongNote "A3"
    SongNote "B3"
    SongNote "C#4"
    SongNote "D#4"
    SongNoteLength $4
    SongNote "F4"
    SongNoteLength $6
    SongNote "C#4"
    SongNoteLength $2
    SongNote "F4"
    SongNoteLength $4
    SongNote "F#4"
    SongNoteLength $6
    SongNote "D4"
    SongNoteLength $2
    SongNote "F#4"
    SongNoteLength $3
    SongNote "E4"
    SongNote "E4"
    SongNote "F#4"
    SongNote "G4"
    SongRepeatSetup $2
        SongNoteLength $3
        SongNote "G#4"
        SongNote "G#3"
    SongRepeat
    SongRepeatSetup $2
        SongNoteLength $1
        SongNote "G#2"
        SongNote "A2"
        SongNote "B2"
        SongNote "C#3"
        SongNote "B2"
        SongNote "A2"
        SongNoteLength $2
        SongNote "G#2"
    SongRepeat
    SongEnd

@tri:
    SongNoteLength $4
    SongNote "G#3"
    SongNote "D#4"
    SongNote "E4"
    SongNote "D#4"
    SongNote "C#4"
    SongNoteLength $3
    SongNote "C4"
    SongNoteLength $1
    SongNote "G#4"
    SongNote "F#4"
    SongNote "E4"
    SongNote "D#4"
    SongRepeatSetup $4
        SongNoteLength $3
        SongNote "C#5"
        SongNoteLength $2
        SongRest
        SongNote "C#5"
        SongNote "C5"
        SongNoteLength $3
        SongNote "G#4"
        SongNoteLength $2
        SongRest
        SongNoteLength $3
        SongNote "A4"
        SongNoteLength $2
        SongRest
        SongNote "A4"
        SongNote "G#4"
        SongNoteLength $3
        SongNote "C5"
        SongNoteLength $2
        SongRest
        SongNoteLength $5
        SongNote "A4"
        SongNoteLength $1
        SongNote "G#4"
        SongNote "F#4"
        SongNote "G#4"
        SongNote "A4"
        SongNote "F#4"
        SongNote "G#4"
        SongNote "G#3"
        SongNote "F#4"
        SongNote "G#3"
        SongNote "E4"
        SongNote "G#3"
        SongNote "D#4"
        SongNote "G#3"
    SongRepeat
    SongRepeatSetup $2
        SongNoteLength $4
        SongNote "C#3"
        SongNote "G#3"
        SongNote "A3"
        SongNoteLength $3
        SongNote "G#3"
        SongNote "C4"
        SongNote "E3"
        SongNote "E3"
        SongNote "G#3"
        SongNote "G#3"
    SongRepeat
    SongNoteLength $2
    SongNote "F#3"
    SongNote "C#4"
    SongNote "G#3"
    SongNote "D#4"
    SongNote "A3"
    SongNote "E4"
    SongNote "B3"
    SongNote "F#4"
    SongNote "C#4"
    SongNote "G#4"
    SongNote "C#4"
    SongNote "G#4"
    SongNote "C#4"
    SongNote "G#4"
    SongNote "C#4"
    SongNoteLength $1
    SongNote "B3"
    SongNote "C#4"
    SongRepeatSetup $3
        SongNoteLength $2
        SongNote "D4"
        SongNote "A4"
    SongRepeat
    SongNote "D4"
    SongNoteLength $1
    SongNote "C#4"
    SongNote "D#4"
    SongNoteLength $2
    SongNote "E4"
    SongNote "A4"
    SongNote "E4"
    SongNote "A4"
    SongNote "E4"
    SongNote "F4"
    SongNote "F#4"
    SongNote "G4"
    SongNote "G#4"
    SongNote "D#4"
    SongNote "C4"
    SongNote "A3"
    SongNote "G#4"
    SongNote "D#4"
    SongNote "C4"
    SongNote "G#3"
    SongRepeatSetup $2
        SongNoteLength $1
        SongNote "C4"
        SongNote "C#4"
        SongNote "D#4"
        SongNote "E4"
        SongNote "D#4"
        SongNote "C#4"
        SongNoteLength $2
        SongNote "C4"
    SongRepeat

@noise:
    SongRepeatSetup $5
        SongNoteLength $1
        .byte $45
        .byte <DrumBeat00SFXData
        .byte $45
        .byte <DrumBeat00SFXData
        SongNoteLength $2
        .byte $67
        .byte $0D
    SongRepeat
    SongRepeatSetup $2
        SongNoteLength $1
        .byte $45
        .byte <DrumBeat00SFXData
    SongRepeat
    SongNoteLength $3
    .byte $5B
    SongRepeatSetup $24
        SongNoteLength $1
        .byte $39
        .byte $0D
        .byte $45
        .byte $0D
        SongRest
        .byte $0D
        .byte $0D
        .byte <DrumBeat00SFXData
    SongRepeat
    SongRepeatSetup $A
        SongNoteLength $1
        .byte $39
        .byte $45
        .byte $03
        .byte $0D
        .byte $67
        .byte $77
        .byte $03
        .byte $0D
    SongRepeat
    SongRepeatSetup $3
        SongNoteLength $3
        .byte $45
    SongRepeat
    .byte $57
