SongTrenchHeader:
    SongHeader NoteLengthsTbl@6, $FF, $00, $02, $03
    .word @sq1, @sq2, @tri, @noise
    .byte $92, $96

@sq1:
    SongRepeatSetup $3
        SongNoteLength $3
        SongNote "D4"
        SongNote "G4"
        SongNoteLength $4
        SongNote "F#4"
        SongNoteLength $3
        SongNote "F4"
        SongNote "G4"
        SongNoteLength $5
        SongNote "E4"
        SongNoteLength $A
        SongNote "E4"
        SongNote "F4"
        SongNoteLength $0
        SongNote "E4"
        SongNoteLength $1
        SongNote "D4"
        SongNote "C4"
        SongNote "A3"
        SongNote "C4"
    SongRepeat
    SongRepeatSetup $5
        SongNoteLength $1
        SongNote "D4"
        SongNote "G4"
        SongNoteLength $5
        SongNote "A4"
        SongNoteLength $1
        SongNote "A3"
        SongNote "D4"
        SongNote "G4"
        SongNoteLength $A
        SongNote "G4"
        SongNote "G#4"
        SongNoteLength $5
        SongNote "A4"
        SongNoteLength $0
        SongNote "A3"
        SongNoteLength $1
        SongNote "D4"
        SongNote "E4"
        SongNote "F4"
        SongNote "G4"
        SongNoteLength $A
        SongNote "G4"
        SongNote "G#4"
        SongNoteLength $7
        SongNote "A4"
        SongNoteLength $1
        SongNote "G4"
        SongNote "F4"
        SongNoteLength $A
        SongNote "F4"
        SongNote "F#4"
        SongNoteLength $7
        SongNote "G4"
        SongNoteLength $1
        SongNote "F4"
        SongNote "E4"
        SongNote "F4"
        SongNote "E4"
        SongNote "D4"
        SongNote "C4"
        SongNoteLength $0
        SongNote "A3"
        SongNote "A#3"
        SongNoteLength $1
        SongNote "A3"
        SongNote "G3"
        SongNote "F3"
    SongRepeat
    SongRepeatSetup $4
        SongNoteLength $0
        SongNote "D4"
        SongNote "B4"
        SongNoteLength $5
        SongNote "C5"
        SongNoteLength $0
        SongNote "D4"
        SongNote "A#4"
        SongNoteLength $5
        SongNote "D5"
        SongNoteLength $0
        SongNote "E4"
        SongNote "A#4"
        SongNoteLength $3
        SongNote "D5"
        SongNoteLength $1
        SongRest
        SongNote "F5"
        SongNoteLength $A
        SongNote "F5"
        SongNote "E5"
        SongNote "D#5"
        SongNote "D5"
        SongNoteLength $4
        SongNote "D5"
        SongNote "D5"
    SongRepeat
    SongRepeatSetup $2
        SongNoteLength $1
        SongNote "D4"
        SongNote "F4"
        SongNoteLength $0
        SongNote "A#4"
        SongNote "B4"
        SongNoteLength $1
        SongNote "C5"
        SongNote "A#4"
        SongNote "A4"
        SongNote "F4"
        SongNote "D4"
        SongNote "E4"
        SongNote "G4"
        SongNoteLength $0
        SongNote "C5"
        SongNote "C#5"
        SongNoteLength $1
        SongNote "D5"
        SongNote "C5"
        SongNote "A#4"
        SongNote "A4"
        SongNote "C5"
        SongNoteLength $3
        SongNote "D5"
        SongNote "F5"
        SongNote "D5"
        SongNote "A4"
    SongRepeat
    SongNote "D4"
    SongNote "E4"
    SongNote "F4"
    SongNote "G4"
    SongNoteLength $4
    SongNote "E4"
    SongNoteLength $1
    SongNote "A3"
    SongNoteLength $2
    SongNote "A4"
    SongNoteLength $1
    SongNote "A3"
    SongNoteLength $2
    SongNote "A4"
    SongNote "A3"
    SongRepeatSetup $4
        SongNoteLength $1
        SongNote "C#2"
        SongNote "D2"
    SongRepeat
    SongRepeatSetup $4
        SongNoteLength $1
        SongNote "C#3"
        SongNote "D3"
    SongRepeat
    SongRepeatSetup $4
        SongNoteLength $1
        SongNote "C4"
        SongNote "D4"
    SongRepeat
    SongNoteLength $3
    SongNote "D6"
    SongNoteLength $A
    SongNote "G5"
    SongNote "F#5"
    SongNote "F5"
    SongNote "E5"
    SongNote "D#5"
    SongNote "D5"
    SongNote "C#5"
    SongNote "C5"
    SongNote "B4"
    SongNote "A#4"
    SongNote "A4"
    SongNote "G4"
    SongNote "F#4"
    SongNote "F4"
    SongNote "E4"
    SongNote "D#4"
    SongEnd

@sq2:
    SongRepeatSetup $6
        SongNoteLength $4
        SongNote "D2"
        SongNote "A2"
        SongNote "F2"
        SongNote "C3"
    SongRepeat
    SongRepeatSetup $2
        SongNoteLength $1
        SongNote "A4"
        SongNote "A#4"
        SongNoteLength $5
        SongNote "D5"
        SongNoteLength $1
        SongNote "G4"
        SongNote "A4"
        SongNote "A#4"
        SongNoteLength $A
        SongNote "C5"
        SongNote "C#5"
        SongNoteLength $5
        SongNote "D5"
        SongNoteLength $0
        SongNote "D5"
        SongNoteLength $1
        SongNote "A4"
        SongNote "B4"
        SongNote "C5"
        SongNote "D5"
        SongNoteLength $4
        SongNote "A4"
        SongNoteLength $3
        SongNote "G4"
        SongNoteLength $2
        SongNote "F4"
        SongNote "E4"
    SongRepeat
    SongRepeatSetup $2
        SongNoteLength $0
        SongNote "D3"
        SongNote "B3"
        SongNoteLength $5
        SongNote "C4"
        SongNoteLength $0
        SongNote "D3"
        SongNote "A#3"
        SongNoteLength $5
        SongNote "D4"
        SongNoteLength $0
        SongNote "E3"
        SongNote "A#3"
        SongNoteLength $3
        SongNote "C4"
        SongNoteLength $1
        SongRest
        SongNote "C5"
        SongNoteLength $A
        SongNote "C5"
        SongNote "B4"
        SongNote "A#4"
        SongNote "A4"
        SongNoteLength $4
        SongNote "A4"
        SongNoteLength $3
        SongNote "F#4"
        SongNoteLength $0
        SongNote "G4"
        SongNote "A4"
        SongNote "F4"
        SongNote "F#4"
        SongNote "C4"
        SongNote "D4"
        SongNote "G#3"
        SongNote "A3"
    SongRepeat
    SongRepeatSetup $4
        SongNoteLength $1
        SongNote "A#3"
        SongNote "D4"
        SongNoteLength $0
        SongNote "G4"
        SongNote "G#4"
        SongNoteLength $1
        SongNote "A4"
        SongNote "G4"
        SongNote "F4"
        SongNote "D4"
        SongNoteLength $2
        SongNote "A#3"
        SongNoteLength $1
        SongNote "C4"
        SongNote "E4"
        SongNote "A#4"
        SongNote "A4"
        SongNote "G4"
        SongNote "F4"
        SongNote "G4"
        SongNote "A4"
        SongNote "A#4"
        SongNote "A4"
        SongNote "A#4"
        SongNote "A4"
        SongNote "A#4"
        SongNote "C5"
        SongNote "D5"
        SongNote "C5"
        SongNote "A#4"
        SongNote "A4"
        SongNoteLength $2
        SongNote "D4"
        SongNoteLength $1
        SongNote "A4"
        SongNote "D5"
        SongNote "D4"
    SongRepeat
    SongNoteLength $3
    SongNote "A#4"
    SongNote "C5"
    SongNote "D5"
    SongNote "A#4"
    SongNoteLength $4
    SongNote "A4"
    SongNoteLength $1
    SongNote "A4"
    SongNote "A4"
    SongNote "E4"
    SongNote "E4"
    SongNote "C#4"
    SongNote "C#4"
    SongNote "A3"
    SongNote "A3"
    SongNoteLength $4
    SongNote "D2"
    SongNote "E2"
    SongNote "F2"
    SongNoteLength $3
    SongNote "G2"
    SongNote "A2"

@tri:
    SongRepeatSetup $5
        SongNoteLength $1
        SongNote "D3"
        SongNote "D3"
        SongNote "D3"
        SongNote "D3"
        SongNote "D3"
        SongNoteLength $A
        SongNote "A#2"
        SongNote "A2"
        SongNote "G2"
        SongNote "F2"
        SongNoteLength $3
        SongNote "D2"
        SongNoteLength $1
        SongRest
        SongNote "D3"
        SongNote "A2"
        SongNote "D3"
        SongNote "A2"
        SongNote "D3"
        SongNoteLength $3
        SongNote "F3"
        SongNote "G2"
        SongNote "C3"
        SongNote "A2"
    SongRepeat
    SongRepeatSetup $3
        SongNoteLength $1
        SongNote "D3"
        SongNote "D3"
        SongNote "F3"
        SongNote "A3"
        SongNoteLength $3
        SongNote "D4"
        SongNoteLength $1
        SongNote "A3"
        SongNote "D4"
        SongNote "F4"
        SongNote "A4"
        SongNoteLength $3
        SongNote "D5"
        SongNoteLength $1
        SongNote "F3"
        SongNote "F3"
        SongNote "C4"
        SongNote "F3"
        SongNote "F4"
        SongNoteLength $0
        SongNote "F3"
        SongNote "E3"
        SongNoteLength $1
        SongNote "F3"
        SongNote "C4"
        SongNote "A3"
        SongNote "A3"
        SongNote "C4"
        SongNote "E4"
        SongNoteLength $2
        SongNote "G4"
        SongNote "A4"
    SongRepeat
    SongRepeatSetup $6
        SongNoteLength $1
        SongNote "A#3"
        SongNoteLength $2
        SongNote "F3"
        SongNote "F3"
        SongNoteLength $1
        SongNote "F3"
        SongNote "A#3"
        SongNote "B3"
        SongNote "C4"
        SongNoteLength $2
        SongNote "G3"
        SongNote "G3"
        SongNoteLength $1
        SongNote "G3"
        SongNote "A#3"
        SongNote "D4"
        SongNote "D4"
        SongNoteLength $2
        SongNote "A3"
        SongNote "A3"
        SongNoteLength $1
        SongNote "A3"
        SongNote "D#4"
        SongNote "C4"
        SongNote "D4"
        SongNoteLength $2
        SongNote "A3"
        SongNote "A3"
        SongNoteLength $1
        SongNote "A3"
        SongNote "G3"
        SongNote "A3"
    SongRepeat
    SongNoteLength $3
    SongNote "G3"
    SongNote "A3"
    SongNote "A#3"
    SongNoteLength $1
    SongNote "C4"
    SongNote "C#4"
    SongNote "D4"
    SongNote "D#4"
    SongNoteLength $3
    SongNote "E4"
    SongNoteLength $1
    SongRest
    SongRest
    SongNote "E4"
    SongNoteLength $A
    SongNote "E4"
    SongNote "D4"
    SongNote "C#4"
    SongNote "B3"
    SongNoteLength $4
    SongNote "A3"
    SongRepeatSetup $3
        SongNoteLength $1
        SongNote "D3"
        SongNote "D4"
    SongRepeat
    SongNote "D3"
    SongNote "D#4"
    SongRepeatSetup $4
        SongNoteLength $1
        SongNote "E3"
        SongNote "E4"
    SongRepeat
    SongRepeatSetup $3
        SongNoteLength $1
        SongNote "F3"
        SongNote "F4"
    SongRepeat
    SongNote "F3"
    SongNote "F#4"
    SongNote "G3"
    SongNote "G4"
    SongNote "G3"
    SongNote "G#4"
    SongRepeatSetup $2
        SongNoteLength $1
        SongNote "A3"
        SongNote "A4"
    SongRepeat

@noise:
    SongRepeatSetup $10
        SongNoteLength $3
        .byte $0D
    SongRepeat
    SongRepeatSetup $1C
        SongNoteLength $2
        .byte $0D
        .byte $0D
        .byte $05
        .byte $0D
    SongRepeat
    SongRepeatSetup $18
        SongNoteLength $1
        .byte $0D
        SongNoteLength $0
        .byte <DrumBeat02SFXData
        .byte $08
        SongNoteLength $1
        .byte $09
        .byte $0D
        .byte <DrumBeat03SFXData
        SongNoteLength $0
        .byte <DrumBeat02SFXData
        .byte $08
        SongNoteLength $1
        .byte $05
        .byte $0D
    SongRepeat
    SongRepeatSetup $3
        SongNoteLength $1
        .byte $0D
        .byte <DrumBeat03SFXData
        .byte $0D
        .byte <DrumBeat03SFXData
        .byte $05
        .byte <DrumBeat03SFXData
        .byte $0D
        .byte <DrumBeat03SFXData
    SongRepeat
    .byte $0D
    .byte $0D
    .byte $05
    .byte $0D
    .byte $0D
    .byte $05
    .byte $0D
    .byte $0D
